version: 2
updates:
  # Enable version updates for pnpm
  - package-ecosystem: "npm"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3