
# Workflow name
name: 'Build and Test'

# Event for the workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

# List of jobs
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0
        with:
          mode: fix
      - name: Apply License Changes
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'
  Build-Test:
    needs: license
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 8.7.6
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build package
        run: pnpm build --filter=@arkejs/client
      - name: Test
        run: pnpm test --filter=@arkejs/client
